using PicDB.Model;
using System;
using System.Collections.Generic;
using System.Text;
using System.Data.SqlClient;
using System.Configuration;
using Serilog;

namespace PicDB.DataAccess
{
    public class DALDatabase : IDAL
    {
        private static readonly string connectionString = ConfigurationManager.AppSettings["database:connectionString"];
        private static readonly SqlConnection connection = new SqlConnection(connectionString);

        public void SavePicture(Picture p)
        {
            string query = "INSERT INTO Picture (Id, Name, Image) OUTPUT INSERTED.Id " + "VALUES (NEWID(), @name, @image); ";
            connection.Open();

            SqlCommand cmd = getCommand(query);
            cmd.Parameters.AddWithValue("@name",p.Name);
            cmd.Parameters.AddWithValue("@image",p.Image);

            p.ID = (Guid)cmd.ExecuteScalar(); //get ID generated by DB

            addPropertiesForPicture(p);
            addPropertiesToPictureMatchers(p);

            connection.Close();
        }

        private void addPropertiesForPicture(Picture p)
        {
            string query = "INSERT INTO PropertyData (Id, Name, TagNumber, Value, Comment) OUTPUT INSERTED.Id " + "VALUES (NEWID(), @name, @tagNumber, @value, @comment)";

            foreach (Property property in p.ExifProperties)
            {
                SqlCommand cmd = getCommand(query);
                cmd.Parameters.AddWithValue("@name", property.Name);
                cmd.Parameters.AddWithValue("@tagNumber", property.TagNumber);
                if(property.Value != null)
                {
                    cmd.Parameters.AddWithValue("@value", property.Value);
                }
                else
                {
                    cmd.Parameters.AddWithValue("@value", DBNull.Value);
                }
                cmd.Parameters.AddWithValue("@comment", property.Comment);
                property.ID = (Guid) cmd.ExecuteScalar(); //get ID generated by DB
         
            }

            foreach (Property property in p.IptcProperties)
            {
                SqlCommand cmd = getCommand(query);
                cmd.Parameters.AddWithValue("@name", property.Name);
                cmd.Parameters.AddWithValue("@tagNumber", property.TagNumber);
                if (property.Value != null)
                {
                    cmd.Parameters.AddWithValue("@value", property.Value);
                }
                else
                {
                    cmd.Parameters.AddWithValue("@value", DBNull.Value);
                }
                cmd.Parameters.AddWithValue("@comment", property.Comment);
                property.ID = (Guid)cmd.ExecuteScalar(); //get ID generated by DB

            }
        }

        private void addPropertiesToPictureMatchers(Picture p)
        {
            string query = "INSERT INTO PicturePropertyData (PictureID, PropertyDataID, PropertyType) " + "VALUES (@pictureID, @propertyDataID, @propertyType)";
            foreach (Property property in p.ExifProperties)
            {
                SqlCommand cmd = getCommand(query);
                cmd.Parameters.AddWithValue("@pictureID", p.ID);
                cmd.Parameters.AddWithValue("@propertyDataID", property.ID);
                cmd.Parameters.AddWithValue("@propertyType", 0);
                cmd.ExecuteNonQuery();
            }

            foreach (Property property in p.IptcProperties)
            {
                SqlCommand cmd = getCommand(query);
                cmd.Parameters.AddWithValue("@pictureID", p.ID);
                cmd.Parameters.AddWithValue("@propertyDataID", property.ID);
                cmd.Parameters.AddWithValue("@propertyType", 1);
                cmd.ExecuteNonQuery();
            }
        }

        private SqlCommand getCommand(string query)
        {
           return new SqlCommand(query, connection);
        }

        public void DeletePictureById(Guid ID)
        {
            if (ID == Guid.Empty) 
            {
                Log.Debug("Nothing to delete... skipping");
                return; 
            }
            Picture p = new Picture();
            p.ID = ID;
            string query = "delete from Picture WHERE Id = " + "@id";
            connection.Open();
            var exifProps = GetPropertiesByIds(GetPropIds(p,0));
            if(exifProps == null)
            {
                connection.Close();
                return;
            }
            var exifPropIds = GetPropIds(p, 0);
            var iptcPropIds = GetPropIds(p, 1);
            deletePropertiesToPictureMatchers(ID);
            deletePropertiesForPicture(exifPropIds);
            deletePropertiesForPicture(iptcPropIds);
            SqlCommand cmd = getCommand(query);
            cmd.Parameters.AddWithValue("@id", ID);
            cmd.ExecuteNonQuery();
            connection.Close();
        }

        private void deletePropertiesToPictureMatchers(Guid ID)
        {
            string query = "delete from PicturePropertyData WHERE PictureID = " + "@id";
            SqlCommand cmd = getCommand(query);
            cmd.Parameters.AddWithValue("@id", ID);
            cmd.ExecuteNonQuery();
        }

        private void deletePropertiesForPicture(IList<Guid> Ids)
        {
            if(Ids.Count == 0) 
            {
                Log.Debug("No properties for picture to delete... skipping");
                return;
            }
            string query = "delete from PropertyData WHERE Id in ({@id})";
            SqlCommand cmd = getCommand(query);
            cmd.AddArrayParameters("@id", Ids);
            cmd.ExecuteNonQuery();
        }

        public Picture GetPictureById(Guid ID)
        {
            Picture p = new Picture();
            string query = "SELECT * from Picture WHERE Id = " + "@id";
            connection.Open();

            SqlCommand cmd = getCommand(query);
            cmd.Parameters.AddWithValue("@id", ID);
            using (var reader = cmd.ExecuteReader())
            {
                if (reader.Read())
                {
                    p.ID = reader.GetGuid(0);
                    p.Name = reader.GetString(1);
                    p.Image = reader.GetString(2);
                    if (!reader.IsDBNull(3))
                    {
                        p.Photographer = GetPhotographerById(reader.GetGuid(3));
                    }
                }
            }

            p.ExifProperties = GetPropertiesByIds(GetPropIds(p,0));
            p.IptcProperties = GetPropertiesByIds(GetPropIds(p,1));
            if(p.ExifProperties.Count == 0)
            {
                connection.Close();
                return null;
            }
            connection.Close();
            return p;
        }

        private IList<Guid> GetPropIds(Picture p, int propertyType)
        {
            IList<Guid> propIds = new List<Guid>();
            string matcherQuery = "SELECT PropertyDataID from PicturePropertyData WHERE PictureID = " + "@id" + " AND PropertyType = " + "@type";
            SqlCommand matcherCmd = getCommand(matcherQuery);
            matcherCmd.Parameters.AddWithValue("@id", p.ID);
            matcherCmd.Parameters.AddWithValue("@type", propertyType);

            using (var matcherReader = matcherCmd.ExecuteReader())
            {
                while (matcherReader.Read())
                {
                    propIds.Add(matcherReader.GetGuid(0));
                }
            }
            //if (propIds.Count == 0)
            //{
            //    return null;
            //}
            return propIds;
        }

        private IList<Property> GetPropertiesByIds(IList<Guid> propIds)
        {
            IList<Property> properties = new List<Property>();
            if (propIds.Count == 0)
            {
                return properties;
            }

            string query = "SELECT * from PropertyData WHERE Id IN ({@propIds})";
            SqlCommand cmd = getCommand(query);
            cmd.AddArrayParameters("@propIds", propIds);

            using (var reader = cmd.ExecuteReader())
            {
                while (reader.Read())
                {
                    Property tempProp = new Property();
                    tempProp.ID = reader.GetGuid(0);
                    tempProp.Name = reader.GetString(1);
                    tempProp.TagNumber = reader.GetInt32(2);
                    if (!reader.IsDBNull(3))
                    {
                        tempProp.Value = reader.GetString(3);
                    }
                    else
                    {
                        tempProp.Value = "";
                    }
                    tempProp.Comment = reader.GetString(4);
                    properties.Add(tempProp);
                }
            }
                return properties;
        }

        public IList<Picture> GetAllPictures()
        {
            IList<Picture> pictures = new List<Picture>();
            string query = "select * from Picture";

            connection.Open();
            SqlCommand cmd = getCommand(query);
            using (var reader = cmd.ExecuteReader())
            {
                while (reader.Read())
                {
                    Picture p = new Picture();
                    p.ID = reader.GetGuid(0);
                    p.Name = reader.GetString(1);
                    p.Image = reader.GetString(2);
                    if (!reader.IsDBNull(3))
                    {
                        p.Photographer = GetPhotographerById(reader.GetGuid(3));
                    }
                    p.ExifProperties = GetPropertiesByIds(GetPropIds(p,0));
                    p.IptcProperties = GetPropertiesByIds(GetPropIds(p,1));
                    pictures.Add(p);
                }
            }
            connection.Close();
            return pictures;
        }

        public IList<Photographer> GetAllPhotographers()
        {
            IList<Photographer> photographers = new List<Photographer>();
            string query = "select * from Photographer";

            connection.Open();

            SqlCommand cmd = getCommand(query);
            using (var reader = cmd.ExecuteReader())
            {
                while (reader.Read())
                {
                    Photographer p = new Photographer();
                    p.ID = reader.GetGuid(0);
                    p.FirstName = reader.GetString(1);
                    p.LastName = reader.GetString(2);
                    if (!reader.IsDBNull(3))
                    {
                        p.Birthday = reader.GetDateTime(3);
                    }
                    photographers.Add(p);
                }
            }

            connection.Close();
            return photographers;
        }

        public Photographer GetPhotographerById(Guid ID)
        {
            Photographer p = new Photographer();
            string query = "SELECT * from Photographer WHERE Id = " + "@id";
            connection.Open();

            SqlCommand cmd = getCommand(query);
            cmd.Parameters.AddWithValue("@id", ID);
            using (var reader = cmd.ExecuteReader())
            {
                if (reader.Read())
                {
                    p.ID = reader.GetGuid(0);
                    p.FirstName = reader.GetString(1);
                    p.LastName = reader.GetString(2);
                    if (!reader.IsDBNull(3))
                    {
                        p.Birthday = reader.GetDateTime(3);
                    }
                }
            }
            connection.Close();
            return p;
        }

        public void SavePhotographer(Photographer p)
        {
            string query = "INSERT INTO Photographer (Id, FirstName, LastName, Birthday) " + "VALUES (NEWID(), @firstname, @lastname, @birthday); ";
            connection.Open();

            SqlCommand cmd = getCommand(query);
            cmd.Parameters.AddWithValue("@firstname", p.FirstName);
            cmd.Parameters.AddWithValue("@lastname", p.LastName);
            if(p.Birthday != null)
            {
                cmd.Parameters.AddWithValue("@birthday", p.Birthday);
            }
            else
            {
                cmd.Parameters.AddWithValue("@birthday", DBNull.Value);

            }

            cmd.ExecuteNonQuery();

            connection.Close();
        }

        public void DeletePhotographerById(Guid ID)
        {
            string query = "delete from Photographer WHERE Id = " + "@id";
            connection.Open();
            SqlCommand cmd = getCommand(query);
            cmd.Parameters.AddWithValue("@id", ID);
            cmd.ExecuteNonQuery();
            connection.Close();
        }

        public void UpdatePhotographer(Photographer p)
        {
            string query = "update Photographer set FirstName = @firstname, LastName = @lastname, Birtday = @birthday where Id = @id";
            connection.Open();
            SqlCommand cmd = getCommand(query);
            cmd.Parameters.AddWithValue("@firstname",p.FirstName);
            cmd.Parameters.AddWithValue("@lastname",p.LastName);
            if (p.Birthday != null)
            {
                cmd.Parameters.AddWithValue("@birthday", p.Birthday);
            }
            else
            {
                cmd.Parameters.AddWithValue("@birthday", DBNull.Value);

            }
            cmd.Parameters.AddWithValue("id",p.ID);
            cmd.ExecuteNonQuery();
            connection.Open();
        }

        public void UpdatePicture(Picture p)
        {
            connection.Open();
            UpdatePropertiesForPicture(p);
            connection.Close();
        }

        private void UpdatePropertiesForPicture(Picture p)
        {
            string query = "update PropertyData set Value= @value, Comment = @comment where Id = @id";
            foreach (Property prop in p.ExifProperties)
            {
                if (prop.Changed)
                {
                    SqlCommand cmd = getCommand(query);
                    cmd.Parameters.AddWithValue("@value", prop.Value);
                    cmd.Parameters.AddWithValue("@comment", prop.Comment);
                    cmd.Parameters.AddWithValue("@id", prop.ID);
                    cmd.ExecuteNonQuery();
                    prop.Changed = false;
                }
            }

            foreach (Property prop in p.IptcProperties)
            {
                if (prop.Changed)
                {
                    SqlCommand cmd = getCommand(query);
                    cmd.Parameters.AddWithValue("@value", prop.Value);
                    cmd.Parameters.AddWithValue("@comment", prop.Comment);
                    cmd.Parameters.AddWithValue("@id", prop.ID);
                    cmd.ExecuteNonQuery();
                    prop.Changed = false;
                }
            }
        }
    }
}
